### ISSUE TITLE
Installation error in Ubuntu+Nix

### ISSUE THREAD

**Issue by meditans** [wavewave/hoodle#32]
Hi,
when I try to install hoodle on ubuntu + nix via this expression:
```
{
  packageOverrides = super:
  let self = super.pkgs;
  in
  {
    haskellDevEnv = self.haskellngPackages.ghcWithPackages (p: with p; [
      # Libraries 
      hoodle
      ghc-mod
    ]);
  };
}
```

I get this error:
```
Building hoodle-core-0.14...
Preprocessing library hoodle-core-0.14...

src/Hoodle/Util.hs:24:8:
    Could not find module ‘Network.URI’
    Perhaps you meant Network.BSD (from network-2.6.0.2)
    Use -v to see a list of the files searched for.
builder for ‘/nix/store/5mj23q9pi75smipxsag0ln7rk8rhg9ik-haskell-hoodle-core-ghc7.8.4-0.14-shared.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/a90pvyjlmq4dhbqib9381n1vbcfh0ask-haskell-hoodle-ghc7.8.4-0.3-shared.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/a90pvyjlmq4dhbqib9381n1vbcfh0ask-haskell-hoodle-ghc7.8.4-0.3-shared.drv’ failed
```
I understand from other github issue that this particular problem is indeed solved. Have you uploaded the hackage package?
Moreover, how do you recommend to install hoodle on ubuntu+nix?

Thanks
Carlo

**Comment by wavewave** [comment]
The new version (`hoodle-core` 0.15 and `hoodle` 0.4) now has updated lower bound on network. 
For nix, you should be able to install hoodle by nix command (like nix-env or nix-build) once I update hoodle on nixpkgs. For ubuntu, probably, installing deps is not very trivial unless ubuntu system has very up-to-date, fully consistent package set. I am planning to register hoodle to stackage, which will solve many dep problems hopefully. Thanks.

**Comment by meditans** [comment]
Hey, thank you for taking the time to upload the new package. In the new haskellng infrastructure, the packages on hackage should be automatically picked up in a few days (I don't know how the external dependencies are added, though, so it's still a good idea to upload the package for the old infrastructure).

**Comment by wavewave** [comment]
Thanks for the message. I also made a pull request of adding hoodle-0.4 to nixpkgs master.
https://github.com/NixOS/nixpkgs/pull/6574
I've tested the commit on my linux machine. :-)
