### ISSUE TITLE
Need cairo >=0.13.0.3 to build

### ISSUE THREAD

**Issue by michamos** [wavewave/hoodle#35]
Hi,

I just managed to build Hoodle-0.4. I did not really use it yet, but so far it seems very nice. Thanks for your great work on Hoodle!

Building went quite smoothly compared to my previous tentative of rebuilding Hoodle 0.3, except for one thing. I ran into the issue gtk2hs/gtk2hs#63, which was fixed in cairo 0.13.0.3. I specified the dependency manually on the command-line ( `cabal install 'cairo>=0.13.0.3' hoodle`), but it would be better to fix it in the cabal file(s) of hoodle itself.

**Comment by wavewave** [comment]
I updated the lower bound for `cairo` and `gtk` and uploaded the new version to hackage.
Thanks!
