### ISSUE TITLE
Failure to build hoodle-types from git version 

### ISSUE THREAD

**Issue by gemana** [wavewave/hoodle#43]
Hi, I like what you've done here! But I can't seem to get hoodle to build from git.

Specifically, I seem to be getting the same exact error as this person:
[https://github.com/wavewave/xournal-types/issues/1](https://github.com/wavewave/xournal-types/issues/1)

It seems to block hoodle-types.
If it helps, I'm using cabal-install 1.22.8.0-2 from the main Arch Linux repository.

**Comment by wavewave** [comment]
37a132e3c1836bb8fcfb0b2d1cff15d87ff13135 dealt with this issue. The commit is quite messed with other things though. But I haven't uploaded the new version on hackage yet and probably, your system picked up the official hackage version. I am uploading the new version soon. Thanks!

**Comment by wavewave** [comment]
uploaded. please check this after running `cabal update` or equivalent.
