### ISSUE TITLE
package install not working

### ISSUE THREAD

**Issue by TitusCornelius** [wavewave/hoodle#44]
When I cabal-install hoodle, I get the conflicting GTK3 GTK2 in the same program error.

To me it seems, that the dependencies for the Cabal package manager are not correctly specified, as otherwise things should be working correctly on my Linux machine. Maybe there is a dependency that upgraded to GTK3 and is now incompatible, maybe sth else entirely.

I did not explicitly compile with the GTK3 flag, so I don't understand why this conflict would arise.
The install was attempted on the latest Ubuntu 15.10 just like you described in the install instructions.

same error as mentioned in https://github.com/wavewave/hoodle/issues/9
Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

**Comment by wavewave** [comment]
gtk2 seems to be finally faded away in major distributions. 
Maybe it's really critical to make hoodle fully compatible with gtk3..

**Comment by TitusCornelius** [comment]
so, for me to install your (really neat looking) application, the only way would be to take your forks of the relevant libraries and compile it from there?

**Comment by TitusCornelius** [comment]
i am gonna try installing the nix package manager and see if I get it working with that..

**Comment by rpglover64** [comment]
@TitusCornelius Did you get it working? I have installed it from Hackage with a few tweaks using `stack`, as well as from source, and I can help you if you like.

**Comment by TitusCornelius** [comment]
@rpglover64 Thanks for the info! No, I temporarily gave up after trying cabal, nix, and installing from source..

Could you give me some instructions? I would still very much love to use this application!

Thank you, Titus

**Comment by Rmano** [comment]
I tried a couple of times to install hoodle, but after pulling *lots* of package there has been a problem every time... I understand that Haskell is a complex environment, but... to have testing and usage I think it is necessary to have a precompiled package, or at least a source bundle were a (non-tech savy) can do a simple `make; make install`. 
Even a static, precompiled binary would be great.  Thanks!

**Comment by rpglover64** [comment]
*Disclaimer: these are in no way official instructions; this is just what worked for me.*

@TitusCornelius @Rmano 

1. Download and install `stack`: http://docs.haskellstack.org/en/stable/install_and_upgrade/#linux  
You could also use a distro-specific installation process or install it from source
2. Run `git clone https://github.com/rpglover64/hoodle.git`
3. Run `cd hoodle`
4. Run `stack build gtk2hs-buildtools`
5. Run `stack build`
6. Wait, fingers crossed.

At some point, `stack` may ask you to let it install a fresh, local (to the user, not the project) version of GHC; I suggest you let it do so, although you can use the `--use-system-ghc` flag to avoid this.

**Comment by RafaelGreenblatt** [comment]
This worked for me; one comment, it wasn't clear to me where the binaries were at the end (maybe because I know nothing about stack or haskell), in the end I did `stack install` (this could be done instead of step 5, right?) and added the appropriate directory (`~/.local/bin`) to my path.

Thanks!  I'd been trying for days to get it to work with `cabal`.

**Comment by rpglover64** [comment]
@RafaelGreenblatt 

> (this could be done instead of step 5, right?)

Yep. `stack install` is just an alias for `stack build --copy-bins`.

The binaries are located in the `.stack-work/install/x86_64-linux/lts-5.8/7.10.3/bin` directory for me; the exact directory will depend on your system's architecture, the snapshot you're using, and the compiler you're using.

If you wanted to avoid `stack install`, you could run `stack --stack-yaml=/PATH/TO/hoodle/stack.yaml exec hoodle` instead, or run `stack exec hoodle` from the directory you built.

**Comment by wavewave** [comment]
added rpglover64's stack instruction into README.md. I am closing this issue. Thanks!

**Comment by swilde** [comment]
Hi, i tried to build hoodle using stack as described above on current arch linux.  I had to replace poppler-0.13.1 with poppler-0.14 in stack.yaml, then it build, but when trying to start hoogle using:
`stack exec hoodle' I still get:
(hoodle:1126): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

**Comment by probonopd** [comment]
You could also check out http://appimage.org - it allows you to bundle dependencies that you cannot expect to be part of the target systems. [Many projects](https://github.com/probonopd/AppImageKit/wiki/AppImages) are already using it (e.g., Krita ships its own Qt and KDE libraries so that you can just download and run Krita without installing anything in your system).

**Comment by wavewave** [comment]
@swilde it's probably because poppler is not compiled with -fgtk3. By default, poppler is installed with gtk2 and then this annoying gtk2/gtk3 mixing problem happens.
