### ISSUE TITLE
Undo branches incorrectly

### ISSUE THREAD

**Issue by rpglover64** [wavewave/hoodle#47]
#### Steps to reproduce:

1. Make a stroke (1)
2. Make a stroke (2)
3. Press undo
4. Make a stroke (3)
5. Press undo

#### Expected:

Only stroke (1) is visible

#### Got:

Stroke (1) and stroke (2) both visible

**Comment by rpglover64** [comment]
Looking into the issue, I believe that it results from the use of [`appendGoLast`](https://github.com/wavewave/hoodle/blob/master/hoodle-types/src/Data/Hoodle/Zipper.hs#L69) in [`addToUndo`](https://github.com/wavewave/hoodle/blob/master/hoodle-core/src/Hoodle/Type/Undo.hs#L38). I would expect state in future points to be dropped; instead, they're retained.

**Comment by wavewave** [comment]
Clearly, this is a bug. I am now examining this issue and your PR. Thanks!

**Comment by wavewave** [comment]
This issue is resolved by #49 !
