### ISSUE TITLE
hoodle installs but crashes on start

### ISSUE THREAD

**Issue by rmahbubani** [wavewave/hoodle#60]
Hi Ian-Woo!  Hope you're well!  I tried to install hoodle on Ubuntu Xenial as per your instructions on http://ianwookim.org/hoodle/installation.html, and it seemed to install without issues.  But when I try to start it up, it crashes with the error message:
"(hoodle:31230): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported"
any idea what I can do to get it to run?
Cheers,
R

**Comment by wavewave** [comment]
Hi, Rakhi, Great to see you here :-)
GTK application should be compiled with either GTK2 or GTK3 only, not allowing mixing each other. Now `hoodle` uses GTK3 by default. In most cases, the usual culprit was poppler library which is pdf rendering C library and haskell binding to it. When you install poppler, turn on `-fgtk3` option, then install `hoodle-render`, `hoodle-core`, `hoodle` after `poppler`.

**Comment by rmahbubani** [comment]
Great, thanks, it starts now with no problems!  Any chance that a user manual will appear soon? :)
