### ISSUE TITLE
Hoodle doesn't compile currently

### ISSUE THREAD

**Issue by SteveElp** [wavewave/hoodle#62]
Is there any hope to get hoodle to compile again?

https://www.reddit.com/r/haskell/comments/7rjwx9/how_to_compile_the_hoodle_gui_app/

It would be really great to update to a more recent GHC version too. GHC 710 is from beginning for 2015 or so.

**Comment by trenkert** [comment]
@wavewave I am wondering if you could get hoodle to compile again, maybe even make it installable via cabal?

**Comment by trenkert** [comment]
I still get this error:

```
poppler-0.14.0: configure
Package poppler uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file
svgcairo-0.13.0.4: configure
Package svgcairo uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file
```
something seems wrong with the configuration...

**Comment by wavewave** [comment]
what tools did you use? stack or cabal. and which version of each tool? if you can show me the full log, that's helpful to me.

**Comment by wavewave** [comment]
no more issue with nix build.
