### ISSUE TITLE
gtk3 support

### ISSUE THREAD

**Issue by wavewave** [wavewave/hoodle#9]
As gtk2hs now support gtk3 since 0.12.5, now is a good time to build hoodle against gtk3 and use all its nicety!

a915b5bee75edf70df760c1ca52d18ff1a48fb2f
is the first successful compilation (but no success in runtime yet)

In run-time, I have an error: 
```
(start-linux-x86_64:23665): Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
```

**Comment by TitusCornelius** [comment]
how can I install a version that does run on gtk2 only and not on gtk3, as I get the same errors and can't fix it

**Comment by wavewave** [comment]
Now hoodle is a fully gtk3-based app.
